# This is a very ugly hack that will only work on Mac computers for now.
# I want a fully functional python environment inside of BRAINS4

set(SPYDER_binary "${CMAKE_CURRENT_BINARY_DIR}/SPYDER/")
set(SPYDER_PYTHON_EXECUTABLE "${${CMAKE_PROJECT_NAME}_PYTHON_EXECUTABLE}")

# create an external project to download SPYDER,
# and configure and build it
ExternalProject_Add(SPYDER
  SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/SuperBuild/SPYDER
  BINARY_DIR ${CMAKE_CURRENT_BINARY_DIR}/SPYDER
    CMAKE_GENERATOR ${gen}
    CMAKE_ARGS
    --no-warn-unused-cli
    -DCMAKE_CXX_COMPILER:STRING=${CMAKE_CXX_COMPILER}
    -DCMAKE_CXX_COMPILER_ARG1:STRING=${CMAKE_CXX_COMPILER_ARG1}
    -DCMAKE_C_COMPILER:STRING=${CMAKE_C_COMPILER}
    -DCMAKE_C_COMPILER_ARG1:STRING=${CMAKE_C_COMPILER_ARG1}
    -DCMAKE_CXX_FLAGS:STRING=${SPYDER_CMAKE_CXX_FLAGS}
    -DCMAKE_C_FLAGS:STRING=${SPYDER_CMAKE_C_FLAGS}
    -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
    -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_INSTALL_PREFIX}
    ${SPYDER_PYTHON_ARGS}
    BUILD_COMMAND /bin/bash ${SPYDER_binary}/spyder_config.sh
    UPDATE_COMMAND ""
    INSTALL_COMMAND ""
    DEPENDS ${SPYDER_DEPENDENCIES}
  )
