# This is a very ugly hack that will only work on Mac computers for now.
# I want a fully functional python environment inside of BRAINS4

set(SPYDER_GLOBAL_ROOT "${CMAKE_CURRENT_BINARY_DIR}")
set(SPYDER_PYTHON_EXECUTABLE "${${CMAKE_PROJECT_NAME}_PYTHON_EXECUTABLE}")

set(SPYDER_PYTHON_ARGS
  -DSPYDER_PYTHON_EXECUTABLE:PATH=${${CMAKE_PROJECT_NAME}_PYTHON_EXECUTABLE}
  -DSPYDER_PYTHON_INCLUDE_DIR:PATH=${${CMAKE_PROJECT_NAME}_PYTHON_INCLUDE}
  -DSPYDER_PYTHON_LIBRARY:FILEPATH=${${CMAKE_PROJECT_NAME}_PYTHON_LIBRARY}
      )

# create an external project to download SPYDER,
# and configure and build it
ExternalProject_Add(SPYDER
  SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/SuperBuild/SPYDER
  BINARY_DIR ${CMAKE_CURRENT_BINARY_DIR}/SPYDER
    CMAKE_GENERATOR ${gen}
    CMAKE_ARGS
    ${ep_common_args}
    -DSPYDER_GLOBAL_ROOT:PATH=${SPYDER_GLOBAL_ROOT}
    -DSPYDER_PYTHON_EXECUTABLE:PATH=${SPYDER_PYTHON_EXECUTABLE}
    BUILD_COMMAND /bin/bash ${SPYDER_GLOBAL_ROOT}/SPYDER/spyder_config.sh
    UPDATE_COMMAND ""
    INSTALL_COMMAND ""
    DEPENDS ${SPYDER_DEPENDENCIES}
  )
