if(DEFINED OpenCV_DIR AND NOT EXISTS ${OpenCV_DIR})
  message(FATAL_ERROR "OpenCV_DIR variable is defined but corresponds to non-existing directory")
endif()

if(NOT DEFINED OpenCV_DIR)
  set(OpenCV_DEPEND OpenCV)
  set(proj OpenCV)
  ExternalProject_add(${proj}
    SOURCE_DIR ${proj}
    BINARY_DIR ${proj}-build

    GIT_REPOSITORY "https://github.com/hjmjohnson/OpenCV.git"
    GIT_TAG "339f97dd675af1cee552a6bb4430689c58559c19"
    CMAKE_ARGS
    --no-warn-unused-cli
    -DBUILD_NEW_PYTHON_SUPPORT:BOOL=OFF
    -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_INSTALL_PREFIX}
    -DCMAKE_CXX_COMPILER:STRING=${CMAKE_CXX_COMPILER}
    -DCMAKE_CXX_COMPILER_ARG1:STRING=${CMAKE_CXX_COMPILER_ARG1}
    -DCMAKE_C_COMPILER:STRING=${CMAKE_C_COMPILER}
    -DCMAKE_C_COMPILER_ARG1:STRING=${CMAKE_C_COMPILER_ARG1}
    -DCMAKE_CXX_FLAGS:STRING=${CMAKE_CXX_FLAGS}
    -DCMAKE_C_FLAGS:STRING=${CMAKE_C_FLAGS}
    -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
    -DBUILD_EXAMPLES:BOOL=OFF
    -DBUILD_SHARED_LIBS:BOOL=ON
    -DBUILD_TESTING:BOOL=OFF
    -DBUILD_TESTS:BOOL=OFF
    -DWITH_FFMPEG:BOOL=OFF
    -DWITH_JASPER:BOOL=OFF
    -DWITH_OPENEXR:BOOL=OFF
    -DWITH_PVAPI:BOOL=OFF
    -DWITH_JPEG:BOOL=OFF
    -DWITH_TIFF:BOOL=OFF
    -DWITH_PNG:BOOL=OFF
    UPDATE_COMMAND ""
    )

   set(OpenCV_DIR ${CMAKE_INSTALL_PREFIX}/share/opencv)
endif(NOT DEFINED OpenCV_DIR)
